package lesson12.FunctionalInterfaces;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.function.Supplier;

// Create a list of n elements generated by supplier
public class Task_14 {
    public static <T> List<T> generate(Supplier<T> supplier, int n) {
        if (n == 0) {
            System.out.println("The quantity of the elements in the list equals to 0");

            return null;
        }

        if (supplier == null) {
            System.out.println("Supplier equals to null");

            return null;
        }

        List<T> generatedStuffCollection = new ArrayList<>();

        for (int i = 0; i < n; i++) {
            generatedStuffCollection.add(supplier.get());
        }

        return generatedStuffCollection;
    }

    public static void main(String[] args) {
        Supplier<UUID> generateUUID = () -> UUID.randomUUID();

        int n = 12;

        List<UUID> uuidCollection = generate(generateUUID, n);

        for (int i = 0; i < uuidCollection.size(); i++) {
            System.out.println(i + 1 + " : " + uuidCollection.get(i));
        }
    }
}
